# Generated by Django 5.1.4 on 2025-01-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
