# Generated by Django 5.1.4 on 2025-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
